version: '2.1'

services:
  server:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    depends_on:
      - postgres
    env_file:
      - env.dev.env
    restart: 'no'
    ports:
      - 8080:8080

  postgres:
    image: postgres:12.2
    env_file:
      - env.dev.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 44312:5432

  migrator:
    build:
      context: .
      dockerfile: ./migrator.Dockerfile
    depends_on:
      - postgres
    env_file:
      - env.dev.env
    restart: 'no'
    volumes:
      - ./project/models/changeLog:/liquibase/changelog

volumes:
  postgres: